platform :ios,'8.0'
use_frameworks!

flutter_application_path = '../my_flutter/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target "MyGame-mobile" do
  install_all_flutter_pods(flutter_application_path)
  pod 'IAPHelper', '~> 1.1'
  pod 'AFNetworking'
end
